language: node_js

matrix:
  include:
  - env: BUILD_TYPE=ONCE
    node_js: 7.0.0
  - env: BUILD_TYPE=ONCE
    node_js: 6.9.5
  - env: BUILD_TYPE=ONCE
    node_js: 6.0.0
  - env: BUILD_TYPE=CHAIN
    node_js: 7.0.0
  - env: BUILD_TYPE=CHAIN
    node_js: 6.9.5
  - env: BUILD_TYPE=CHAIN
    node_js: 6.0.0

before_install:
  - npm -g install npm@5.0.0
  - npm install -g bower
  - npm install -g gulp

install:
  - npm link
  - bower install

script:
  - react-orcrist --version
  - if [[ $BUILD_TYPE == 'ONCE' ]]; then react-orcrist --init test; fi
  - if [[ $BUILD_TYPE == 'ONCE' ]]; then cd test; fi
  - if [[ $BUILD_TYPE == 'ONCE' ]]; then npm install; fi
  - if [[ $BUILD_TYPE == 'ONCE' ]]; then npm run build; fi
  - if [[ $BUILD_TYPE == 'CHAIN' ]]; then mkdir test; fi
  - if [[ $BUILD_TYPE == 'CHAIN' ]]; then cd test; fi
  - if [[ $BUILD_TYPE == 'CHAIN' ]]; then react-orcrist --init; fi
  - if [[ $BUILD_TYPE == 'CHAIN' ]]; then npm install; fi
  - if [[ $BUILD_TYPE == 'CHAIN' ]]; then npm run build; fi
  - gulp build

branches:
  only:
    - master
